config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')
  get '/books/:id/similar_books' => 'books#search_similar_books',
  as: :search_similar_books
end

app/models/Book.rb
class Book < ApplicationRecord
  before_save :titleize

  def self.all_genres ; %W[#{"Science fiction"} Drama #{"Action and Adventure"} Romance Mystery Horror] ; end
    validates :title, :presence => true
    validates :genre, :inclusion => {:in => Book.all_genres}
    validates :description, :presence => true
    validates :ISBN_number, :presence => true, :unless => :published_after_1967?
    validates :publish_date, :presence => true
    validates :author, :presence => true

  def published_after_1967?
    publish_date && publish_date < Date.parse('1 Jan 1967')
  end

  def titleize
    self.title = title.split.each{|x| x.capitalize!}.join(' ')
  end

  def self.similar_books(book)
    Book.where author: book.author
  end

  def search_similar_books
  @book = Book.find(params[:id])
  if @book.author.nil? || @book.author.empty?
    flash[:warning]= "'#{@book.title}' has no author info"
    redirect_to books_path
  else
    @books = Book.similar_books(@book)
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if !params.key?(:genres)
      params[:genres] = {}
    end
    permitted = params.permit(:sort, genres: params[:genres].keys)
    sort = permitted[:sort] || session[:sort]

    case sort
      when 'title'
      ordering, @title_header = {:title => :asc}, 'hilite'
      when 'publish_date'
      ordering, @date_header = {:publish_date => :asc}, 'hilite'
    end

    @all_genres = Book.all_genres
    @selected_genres = permitted[:genres] || session[:genres] || {}
    if @selected_genres == {}
      @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
    end

    @selected_author = params[:author]|| ""

    if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end

    @books = Book.where(genre: @selected_genres.keys).order(ordering)
  end

  def show                      #will render app/views/books/show.html.haml by default
    id = params[:id]            #retrieve books ID from URI route
    @book = Book.find(id)       #look up book by unique ID
  end

  def create
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:description,:ISBN_number,:publish_date,:author)
    @book = Book.new(params[:book])

    if @book.save
      flash[:notice] = "#{@book.title} was successully created."
      redirect_to books_path
    else
      render 'new' # note, new template can access @movie's field values!
    end
  end

  def new
    @book = Book.new      
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:description,:ISBN_number,:publish_date,:author)

    if @book.update_attributes!(permitted)
      flash[:notice] = "#{@book.title} was successfully updated."
      redirect_to book_path(@book)
    else
      render 'edit' #note, 'edit' template can access @movie's field values!
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "#{@book.title} was successfully deleted."
    redirect_to book_path(@book)
  end


  def search_similar_books
    @book = Book.find(params[:id])

    if @book.author.nil? || @book.author.empty?
      flash[:warning]= "'#{@book.title}' has no author info"
      redirect_to books_path
    else
      @books = Book.similar_books(@book)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book_form.html.haml
= label :book, :title, 'Title'
= text_field :book, 'title'

= label :book, :genre, 'Genre'
= select :book, :genre, Book.all_genres

= label :book, :ISBN_number, 'ISBN_number'
= text_field :book, 'ISBN_number'

= label :book, :publish_date, 'Released On'
= date_select :book, :publish_date

= label :book, :author, 'Author'
= text_field :book, 'author'

app/views/books/_book_index_form.html.haml
%tr
    %td= book.title
    %td= book.genre
    %td= book.ISBN_number
    %td= book.author
    %td= book.publish_date
    %td= link_to "More about #{book.title}", book_path(book)

app/views/books/edit.html.haml
%h2 Edit Book

= form_tag book_path(@book), :method => :put do

  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error

  = render :partial => 'book_form'
  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 All Books
= form_tag books_path, :method => :get, :id => 'genres_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'
%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title'), :id => 'title_header'
      %th Genre
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
      %th Author
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.publish_date
        %td= book.author
        %td= link_to "More about #{book.title}", book_path(book)

= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag books_path, :method => :post do
  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error

  = render :partial => 'book_form'
  = submit_tag 'Save Changes'

  = link_to 'Back to book list', books_path

app/views/books/search_similar_books.html.haml
%h1 Similar books to #{@book.title}

%table#similar_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th Publish Date
      %th Author
      %th ISBN Number
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.publish_date
        %td= book.author
        %td= book.ISBN_number
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/show.html.haml
%h2 Details about #{@book.title}

%ul#details
  %li
    Genre:
    = @book.genre
  %li
    Description:
    = @book.description
  %li
    ISBN_number:
    = @book.ISBN_number
  %li
    Released on:
    = @book.publish_date.strftime("%B %d, %Y")

%h3 Description:
%p#description= @book.description

= link_to 'Edit info', edit_book_path(@book)
= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)
= link_to 'Delete', book_path(@book), :method => :delete
= link_to 'Back to book list', books_path

app/views/layouts/application.html.haml
%html
  %head
    %title MyFavouriteBooks!
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield